export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_CONFIRM = "REGISTER_CONFIRM"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const FORGET_PASSWORD_CONFIRM = "FORGET_PASSWORD_CONFIRM"
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS"
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS"

